version: "3"
services:
  api:
    build:
      context: ./back
    ports:
      - 3001:3001
    restart: always
    environment:
      JWT_SECRET: 1234567899oiuywriufbdsfldsv
    volumes:
      - ./back:/app

  # web:
  #   build:
  #     context: ./front
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - api
  #   restart: always
  #   volumes:
  #     - ./front:/app
