name: Push Back docker image to Dockerhub

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Back to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Dokcerhub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Extract metadata (tags, labels) from Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/xops-project-back:latest

      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v3
        with:
          context: ./back
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/xops-project-back:latest
          labels: ${{ steps.meta.outputs.labels }}
